### ISSUE TITLE
Marca v0.1

### ISSUE THREAD

**Issue by davegonzalez** [davegonzalez/marca-roadmap#5]
what makes this an MVP
- [ ] bookmarking
- [ ] tagging of bookmarks for filtering
- [ ] collections of bookmarks, shareable or private 
- [ ] user auth and purchase
- [ ] archiving
- [ ] read it later 
- [ ] export data to Json, markdown

Would ideally have
- [ ] some app support, iOS or android
- [ ] bookmarklet
- [ ] chrome extension

Nice to have
- [ ]  keybindings ala linear.app or superhuman

Later
- [ ] annotating
- [ ] read your queue notification
- [ ] sync to GitHub 
- [ ] sync to local files
